#!/usr/bin/perl
$n = <>;

%h = (X=>1, O=>2, T=>3, '.'=>0);

for $line (1 .. $n) {
	@m = ();
	for (1..4) {
		$t = <>;
		chomp $t;
		push @m, $t;
	}
	<>;
	@row = ();
	@col = ();
	for ($i = 0; $i <= $#m; $i++) {
		$m[$i] =~ s/[\r\n]//g;
		@t = split //, $m[$i];
		for $k(0 .. 3) {
			#print "$_\n";
			$t[$k] =~ s/[XOT\.]/$h{$&}/eg;
			$row[$i] .= $t[$k];
			$col[$k] .= $t[$k];
		}
	}
	my $ch1 = check(1, @row);
	my $ch2 = check(0, @col);

	if ($ch1 == 10 or $ch2 == 10) {
		print "Case #$line: X won\n";
	} elsif ($ch1 == 20 or $ch2 == 20) {
		print "Case #$line: O won\n";
	} elsif ($ch1 == 1 or $ch2 == 1) {
		print "Case #$line: Game has not completed\n";
	} else {
		print "Case #$line: Draw\n";
	}
	#print "@row\n";
	#print "@col\n";
}

sub check {
	my $flag = shift;
	my @l = @_;
	if ($flag) {
		push @l, (substr($l[0], 0, 1) .  substr($l[1], 1, 1) . substr($l[2], 2, 1) . substr($l[3], 3, 1));
	} else {
		push @l, (substr($l[0], 3, 1) .  substr($l[1], 2, 1) . substr($l[2], 1, 1) . substr($l[3], 0, 1));
	}
	#print $l[4], "\n";

	my $not = 0;
	for (@l) {
		my $t = $_;
		$t =~ s/3/1/;
		if ($t eq "1111") {
			return 10; #"X won";
		}
		$t = $_;
		$t =~ s/3/2/;
		if ($t eq "2222") {
			return 20; #"O won";
		}
		$t = $_;
		$t =~ s/0/1/g;
		if ($t eq "1111") {
			$not = 1;
		}

		$t = $_;
		$t =~ s/0/2/g;
		if ($t eq "2222") {
			$not = 1;
		}
	}
	return $not;
}
