#!/usr/bin/perl
no warnings "all";

open( FILE, "data.txt" ) or die("Unable to open file");    # open file
open( OFILE, '> dataout.txt' );
@data = <FILE>;    # read file into an array

$count         = 1;
$numberofcases = 0;
$caseline      = 1;
$casenumber    = 1;
foreach $line (@data) {

	#print $line;
	if ( $count != 1 ) {
		
		#Collecting one case
		if ( $caseline == 1 ) { $row1 = $line; }
		if ( $caseline == 2 ) { $row2 = $line; }
		if ( $caseline == 3 ) { $row3 = $line; }
		if ( $caseline == 4 ) {
			$row4 = $line;
			$caseResult = 4;
			$dotfound   = 0;
			@matrix     = "";

			# All lines collected execute algo :)
			@array1 = split( //, $row1 );
			@array2 = split( //, $row2 );
			@array3 = split( //, $row3 );
			@array4 = split( //, $row4 );
			$col1   = @array1[0] . @array2[0] . @array3[0] . @array4[0];
			$col2   = @array1[1] . @array2[1] . @array3[1] . @array4[1];
			$col3   = @array1[2] . @array2[2] . @array3[2] . @array4[2];
			$col4   = @array1[3] . @array2[3] . @array3[3] . @array4[3];
			$dia1   = @array1[0] . @array2[1] . @array3[2] . @array4[3];
			$dia2   = @array1[3] . @array2[2] . @array3[1] . @array4[0];

			push( @matrix, $row1 );
			push( @matrix, $row2 );
			push( @matrix, $row3 );
			push( @matrix, $row4 );
			push( @matrix, $col1 );
			push( @matrix, $col2 );
			push( @matrix, $col3 );
			push( @matrix, $col4 );
			push( @matrix, $dia1 );
			push( @matrix, $dia2 );

FOO:		foreach $value (@matrix) {
				if ( checkX($value) == 1 ) {
					$caseResult = 1;
					last FOO;
				}
				if ( checkO($value) == 1 ) {
					$caseResult = 2;
					last FOO;
				}
				if ( checkdot($value) == 1 ) {
					$dotfound = 1;
				}
			}

			if ( $caseResult == 4 && $dotfound == 0 ) {
				$caseResult = 3;
			}

			if ( $caseResult == 1 ) {
				print OFILE "Case #" . $casenumber . ": X won". "\n";
			}
			if ( $caseResult == 2 ) {
				print OFILE "Case #" . $casenumber . ": O won". "\n";
			}
			if ( $caseResult == 3 ) {
				print OFILE "Case #" . $casenumber . ": Draw". "\n";
			}
			if ( $caseResult == 4 ) {
				print OFILE "Case #" . $casenumber . ": Game has not completed". "\n";
			}
		}
		if ( $caseline == 5 ) { $caseline = 0; $casenumber++; }
		$caseline++;
	}
	else { $numberofcases = $line; }
	$count++;
}

#Write to the output file.

close(FILE);    # close file
close(OFILE);

sub checkX {
	$string = $_[0];
	if (   index( $string, 'X' ) != -1

		&& index( $string, '.' ) == -1
		&& index( $string, 'O' ) == -1 )
	{
		return 1;
	}
	else {
		return 0;
	}
}

sub checkO {
	$string = $_[0];
	if (   index( $string, 'O' ) != -1

		&& index( $string, '.' ) == -1
		&& index( $string, 'X' ) == -1 )
	{
		return 1;
	}
	else {
		return 0;
	}
}

sub checkdot {
	$string = $_[0];
	if ( index( $string, '.' ) != -1 ) {
		return 1;
	}
	else {
		return 0;
	}
}

